name: Zotero to Readwise Automation

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"  # Runs at 3:00 AM UTC every 6 hours (you can adjust this)

jobs:
  zotero-to-readwise-automation:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install zotero2readwise

      # Debug: Check the version of zotero2readwise installed
      - name: Check installed zotero2readwise version
        run: |
          pip show zotero2readwise

      # Debug: List the files in the relevant directory to ensure you're using the correct one
      - name: List files in the site-packages directory
        run: |
          ls /opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/zotero2readwise/

      # Debug: Check the contents of zotero.py
      - name: Print the first 20 lines of zotero.py
        run: |
          head -n 20 /opt/hostedtoolcache/Python/3.9.22/x64/lib/python3.9/site-packages/zotero2readwise/zotero.py

      # Download the Python script needed for automation
      - name: Download run.py from your fork
        run: |
          curl https://raw.githubusercontent.com/daleharris0509/Zotero2Readwise/master/zotero2readwise/run.py -o run.py

      # Run the automation
      - name: Run automation
        run: python run.py ${{ secrets.READWISE_TOKEN }} ${{ secrets.ZOTERO_KEY }} ${{ secrets.ZOTERO_ID }}
