name: Zotero to Readwise Automation

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours at 3:00 AM UTC

jobs:
  zotero-to-readwise-automation:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # Step 2: Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Upgrade pip and force install dependencies
      - name: Install dependencies (with force install)
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/pyzotero/pyzotero.git  # Force install pyzotero from GitHub
          pip install --upgrade zotero2readwise  # Force upgrade zotero2readwise

      # Step 4: Debugging: Show installed versions of pyzotero and zotero2readwise
      - name: Show installed pyzotero and zotero2readwise versions
        run: |
          pip show pyzotero
          pip show zotero2readwise

      # Step 5: Download run.py from your fork (make sure to reference your fork)
      - name: Download the Python script needed for automation
        run: |
          curl https://raw.githubusercontent.com/daleharris0509/Zotero2Readwise/master/zotero2readwise/run.py -o run.py

      # Step 6: Run the automation
      - name: Run automation
        run: python run.py ${{ secrets.READWISE_TOKEN }} ${{ secrets.ZOTERO_KEY }} ${{ secrets.ZOTERO_ID }}
